image: pobj

stages:
- test

TME-4:
  script: >
    /home/pobj/run5.sh -id TME-4 -name TME-4
    pobj.multiset.test.HashMultiSetTest
    pobj.multiset.test.IteratorTest
    pobj.multiset.test.CollectionTest
  artifacts:
    reports:
      junit: report.xml

TME-5:
  script: >
    /home/pobj/run5.sh -id TME-5 -name TME-5
    pobj.multiset.test.HashMultiSetTest2
  artifacts:
    reports:
    junit: report.xml